#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_DRAW_SW_COMPLEX 1
#define LV_COLOR_16_SWAP 1

#define LV_FONT_MONTSERRAT_8  0
#define LV_FONT_MONTSERRAT_10 0
#define LV_FONT_MONTSERRAT_12 0
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 0
#define LV_FONT_MONTSERRAT_18 0

#define LV_USE_DEMO_WIDGETS 0
#define LV_USE_DEMO_BENCHMARK 0
#define LV_USE_DEMO_STRESS 0
#define LV_USE_DEMO_MUSIC 0

#define LV_USE_CHART 0
#define LV_USE_KEYBOARD 0
#define LV_USE_TABVIEW 0

#define LV_USE_BIDI 0
#define LV_USE_ARABIC_PERSIAN_CHARS 0

#endif